name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.17.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  firebase_database: ^10.5.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  google_sign_in: ^6.2.1
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#ffffff"
  image: images/plant512.png

flutter:
  uses-material-design: true
  assets:
    - images/
