// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv69NX_aeKcU0nipezrw0ZXPuZZRlERPw',
    appId: '1:97374961738:web:a6a492045b5fe8436ba6b3',
    messagingSenderId: '97374961738',
    projectId: 'vungocminhdatn',
    authDomain: 'vungocminhdatn.firebaseapp.com',
    storageBucket: 'vungocminhdatn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtbHxvJHNUKzTi0WLtU8jPHweAd_bLXEI',
    appId: '1:97374961738:ios:6bb2e69499be06c86ba6b3',
    messagingSenderId: '97374961738',
    projectId: 'vungocminhdatn',
    storageBucket: 'vungocminhdatn.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtbHxvJHNUKzTi0WLtU8jPHweAd_bLXEI',
    appId: '1:97374961738:ios:6bb2e69499be06c86ba6b3',
    messagingSenderId: '97374961738',
    projectId: 'vungocminhdatn',
    storageBucket: 'vungocminhdatn.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv69NX_aeKcU0nipezrw0ZXPuZZRlERPw',
    appId: '1:97374961738:web:69e19654269c9f656ba6b3',
    messagingSenderId: '97374961738',
    projectId: 'vungocminhdatn',
    authDomain: 'vungocminhdatn.firebaseapp.com',
    storageBucket: 'vungocminhdatn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzeeKSSMLTWdmCEcD_fSw00Y24YBx3ucY',
    appId: '1:97374961738:android:0ec8b1256ed1276e6ba6b3',
    messagingSenderId: '97374961738',
    projectId: 'vungocminhdatn',
    storageBucket: 'vungocminhdatn.appspot.com',
  );

}